name =input ("Enter Your Full Name :")
# result=len(name)
# result=name.find(" ")
# result =name.rfind("a")
# result =name.capitalize()
# result=name.upper()
# result =name.lower()
# result =name.isdigit()
result =name.isalpha()

print(result)