adjective1=input("Enter a adjective (description) : ")
noun1=input("Enter a noun (person ,Place,thing) : ")
adjective2=input("Enter a adjective (description) : ")
verb1=input("Enter a verb with ing : ")
adjective3=input("Enter a adjective (description) : ")

print(f"Today I went to a {adjective1} Zoo")
print(f"In an exhibit, I saw a {noun1} ")
print(f"{noun1} was {adjective2} and {verb1}")
print(f"I was {adjective3}")